/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextBox1 = new javax.swing.JTextField();
        TextBox4 = new javax.swing.JTextField();
        TextBox3 = new javax.swing.JTextField();
        TextBox2 = new javax.swing.JTextField();
        TextBox5 = new javax.swing.JTextField();
        Tittle = new javax.swing.JLabel();
        Button1 = new javax.swing.JButton();
        Question1 = new javax.swing.JLabel();
        Question2 = new javax.swing.JLabel();
        Question4 = new javax.swing.JLabel();
        Question3 = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        Question5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBox1ActionPerformed(evt);
            }
        });

        TextBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBox4ActionPerformed(evt);
            }
        });

        TextBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBox3ActionPerformed(evt);
            }
        });

        TextBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBox2ActionPerformed(evt);
            }
        });

        TextBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBox5ActionPerformed(evt);
            }
        });

        Tittle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Tittle.setText("BIOLOGY QUIZ!");

        Button1.setText("Submit");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Question1.setText("1.  Whats the biggest organ in your body?");

        Question2.setText("2. The bones that make up  your spine are called____");

        Question4.setText("4.What does the innermost of the bone contain?");

        Question3.setText("3.Another name for your voice box is_____");

        Question5.setText("5. When do babies start to shed tears?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(Tittle))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(TextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Question1)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(TextBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Question5)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(TextBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Question4))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TextBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(score, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TextBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Question2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Button1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Question3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Label6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Tittle)
                .addGap(18, 18, 18)
                .addComponent(Question1)
                .addGap(4, 4, 4)
                .addComponent(TextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Question2)
                    .addComponent(Button1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Question3)
                    .addComponent(jLabel1)
                    .addComponent(Label6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Question4)
                    .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(Question5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBox1ActionPerformed

    private void TextBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBox4ActionPerformed

    private void TextBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBox3ActionPerformed

    private void TextBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBox2ActionPerformed

    private void TextBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBox5ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
     
        Label6.Text = (marks 
                    + (Space(1) + "/ 5"));
        switch (marks) {
            case 0:
                MsgBox("oof you failed");
                break;
            case 1:
                MsgBox("you got a 1, you need to start trying");
                break;
            case 2:
                MsgBox("you have a 2, you could do better");
                break;
            case 3:
                MsgBox("you passed!");
                break;
            case 4:
                MsgBox("Almost there");
                break;
            case 5:
                MsgBox("You aced it!");
                break;
        }


// TODO add your handling code here:
    }//GEN-LAST:event_Button1ActionPerformed
public class Form1 {

    private int marks = 0;

    private final void Button1_Click(object sender, EventArgs e) {
        if ((TextBox1.Text.ToUpper == "SKIN")) {
            marks++;
        }

        if ((TextBox2.Text.ToUpper == "VERTEBRAE")) {
            marks++;
        }

        if ((TextBox3.Text.ToUpper == "LARYNX")) {
            marks++;
        }

        if ((TextBox4.Text.ToUpper == "BONE MARROW")) {
            marks++;
        }
        else if ((TextBox4.Text.ToUpper == "BONEMARROW")) {
            marks++;
        }

        if ((TextBox5.Text.ToUpper == "1 MONTH")) {
            marks++;
        }
        else if ((TextBox5.Text.ToUpper == "ONE MONTH")) {
            marks++;
        }

        Label6.Text = (marks 
                    + (Space(1) + "/ 5"));
        switch (marks) {
            case 0:
                MsgBox("oof you failed");
                break;
            case 1:
                MsgBox("you got a 1, you need to start trying");
                break;
            case 2:
                MsgBox("you have a 2, you could do better");
                break;
            case 3:
                MsgBox("you passed!");
                break;
            case 4:
                MsgBox("Almost there");
                break;
            case 5:
                MsgBox("You aced it!");
                break;*/
        }
    }

    private final void Form1_Load(object sender, EventArgs e) {
        MsgBox("You will be asked 5 questions. Can you answer them all?");
    }
}    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Question1;
    private javax.swing.JLabel Question2;
    private javax.swing.JLabel Question3;
    private javax.swing.JLabel Question4;
    private javax.swing.JLabel Question5;
    private javax.swing.JTextField TextBox1;
    private javax.swing.JTextField TextBox2;
    private javax.swing.JTextField TextBox3;
    private javax.swing.JTextField TextBox4;
    private javax.swing.JTextField TextBox5;
    private javax.swing.JLabel Tittle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
